server:
  port: ${APP_PORT:8094}
spring:
  application:
    name: authorization
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ncba} #?createDatabaseIfNotExist=true
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      continue-on-error: true
